// includes/widgets/shop-demo/article-teaser-widget/article-teaser-widget.jsx
/**
 * Copyright 2016 aixigo AG
 * Released under the MIT license.
 * http://laxarjs.org/license
 *
 * compile using
 * > babel -m amd -d . article-teaser-widget.jsx
 */
import React from 'react';

export default {
   name: 'article-teaser-widget',
   injections: [ 'axEventBus', 'axFeatures', 'axReactRender' ],
   create: function( eventBus, features, reactRender ) {

      var resources = { article: null };
      const articleResource = features.article.resource;
      eventBus.subscribe( 'didReplace.' + articleResource, event => {
         resources.article = event.data;
         render();
      } );

      function addToCart() {
         const actionName = features.confirmation.action;
         eventBus.publish( 'takeActionRequest.' + actionName, {
            action: actionName
         } );
      }

      function render() {
         reactRender( <div>
            <ArticleHeader isSelected={ !!resources.article } />
            <ArticleTeaser article={ resources.article || { name: 'No article selected' } } />
            <div className='clearfix'>
               <button type='button'
                       className={ `btn pull-right ${resources.article ? 'btn-info' : 'ax-disabled'}` }
                       onClick={addToCart}><i className='fa fa-shopping-cart'></i> Add to Cart</button>
            </div>
         </div> );
      }

      return { onDomAvailable: render };
   }
};

const ArticleHeader = React.createClass({
   render() {
      const { isSelected } = this.props;
      return <h3 className={ `ax-function-point ${isSelected ? 'app-selection' : ''}` }>
         <i className='fa fa-search'></i> Details
      </h3>;
   }
});

const ArticleTeaser = React.createClass({
   render() {
      const { article } = this.props;
      return <div className={ 'app-teaser-wrapper clearfix' + (article.id && ' app-selection') }>
         <h4 className={ article.id || 'app-no-selection' }>{ article.name }</h4>
         <div className='row'>
            <div className='col col-md-12 app-teaser-image-wrapper'>
               { article.pictureUrl && <img className='app-teaser-image' src={ article.pictureUrl } /> }
            </div>
         </div>
         <div className='row'>
            <div className='col col-md-12'>
               <dl className='dl-horizontal'>
                  <dt className={ article.id || 'ax-disabled' }>Art. ID</dt>
                  <dd>{ article.id }</dd>

                  <dt className={ article.id || 'ax-disabled' }>Description</dt>
                  <dd dangerouslySetInnerHTML={{__html: article.htmlDescription}}></dd>

                  <dt className={ article.id || 'ax-disabled' }>Price</dt>
                  <dd>{ this.formattedPrice( article.price ) }</dd>
               </dl>
            </div>
         </div>
      </div>;
   },

   formattedPrice( price ) {
      return price == null ? null : ('€ ' + price.toFixed( 2 ));
   }

});

// application/widgets/article-teaser-widget/article-teaser-widget.vue
<template>
<div>
   <h3 :class="`ax-function-point ${article.id ? 'app-selection' : ''}`">
      <i class='fa fa-search'></i> Details
   </h3>
   <div class="app-teaser-wrapper clearfix"
      :class="{ 'app-selection' : article.id }">
      <h4 :class="{ 'app-no-selection' : !article.id }">{{ article.name || 'No article selected' }}</h4>
      <div class="row">
         <div class="col col-md-12 app-teaser-image-wrapper">
            <img v-if="article.pictureUrl" class='app-teaser-image' :src="article.pictureUrl" />
         </div>
      </div>
      <div class="row">
         <div class="col col-md-12">
            <dl class="dl-horizontal">
               <dt :class="{ 'ax-disabled': article.id }">Art. ID</dt>
               <dd>{{ article.id }}</dd>

               <dt :class="{ 'ax-disabled': article.id }">Description</dt>
               <dd v-html="article.htmlDescription"></dd>

               <dt :class="{ 'ax-disabled': article.id }">Price</dt>
               <dd>{{ formatted( article.price ) }}</dd>
            </dl>
         </div>
      </div>
   </div>
   <div class="clearfix">
      <button type="button"
          class="btn pull-right"
          :class="{ 'btn-info': article.id, 'ax-disabled': !article.id }"
          @click="addToCart()"><i class="fa fa-shopping-cart"></i> Add to Cart</button>
   </div>
</div>
</template>


<script>
/**
 * Copyright 2017 aixigo AG
 * Released under the MIT license.
 * http://laxarjs.org/license
 */
export default {
   data: () => ({ article: { id: null } }),
   created() {
      this.eventBus.subscribe( `didReplace.${this.features.article.resource}`, event => {
         this.article = event.data || { id: null };
      } );
   },
   methods: {
      formatted( price ) {
         return price == null ? '' : `€ ${price.toFixed( 2 )}`;
      },
      addToCart() {
         const { action } = this.features.confirmation;
         this.eventBus.publish( `takeActionRequest.${action}`, { action } );
      }
   }
};
</script>
